const importArray = [
	{
		"Wine": "Constantia Glen Three",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Constantia glen",
		"Area": "Constantia",
		"Country": "Sør Afrika",
		"Price": "220,2",
		"Tasting": "mai.17",
		"Host": "nib",
		"MJ": "15",
		"HS": "16,5",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "16",
		"JR": "0",
		"Score": "16,10"
	},
	{
		"Wine": "Fennocio Barbaresco",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "Fennocio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "199,9",
		"Tasting": "mai.17",
		"Host": "nib",
		"MJ": "16",
		"HS": "16",
		"BAL": "16",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "0",
		"Score": "15,80"
	},
	{
		"Wine": "Proddutori del Barbaresco",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Pro. Del. Barbaresco",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "289,9",
		"Tasting": "mai.17",
		"Host": "nib",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "15",
		"NIB": "15,5",
		"JR": "0",
		"Score": "15,40"
	},
	{
		"Wine": "Weinert Carrascal",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Bod. y Cavas de Weinert",
		"Area": "Medoza",
		"Country": "Argentina",
		"Price": "159,9",
		"Tasting": "mai.17",
		"Host": "nib",
		"MJ": "15",
		"HS": "15",
		"BAL": "15,5",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "0",
		"Score": "15,30"
	},
	{
		"Wine": "Gattinara Nervi",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Az. Vit. Nervi",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "229,9",
		"Tasting": "mai.17",
		"Host": "nib",
		"MJ": "14,5",
		"HS": "15",
		"BAL": "15,5",
		"LPW": "14,5",
		"NIB": "15",
		"JR": "0",
		"Score": "14,90"
	},
	{
		"Wine": "Ch. La. Lerthe",
		"Type": "Rodvin",
		"Year": "2011",
		"Producer": "Ch. La. Lerthe",
		"Area": "Ch. Du pape",
		"Country": "Frankrike",
		"Price": "314,9",
		"Tasting": "mai.17",
		"Host": "nib",
		"MJ": "14",
		"HS": "14,5",
		"BAL": "14,5",
		"LPW": "14",
		"NIB": "15",
		"JR": "0",
		"Score": "14,40"
	},
	{
		"Wine": "Ch. Musar",
		"Type": "Rodvin",
		"Year": "2002",
		"Producer": "Gaston Hochar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "360",
		"Tasting": "apr.18",
		"Host": "mj",
		"MJ": "18,0",
		"HS": "17,5",
		"BAL": "",
		"LPW": "",
		"NIB": "17,5",
		"JR": "17,5",
		"Score": "17,63"
	},
	{
		"Wine": "Felisia Fontarello",
		"Type": "Rodvin",
		"Year": "2011",
		"Producer": "Fatt. di Felsina",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "400",
		"Tasting": "sep.17",
		"Host": "mj",
		"MJ": "17,0",
		"HS": "17,5",
		"BAL": "17,5",
		"LPW": "",
		"NIB": "",
		"JR": "16,5",
		"Score": "17,13"
	},
	{
		"Wine": "Montevertine Le Pergole Torte",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Az. Agr. Montevertine",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "759,9",
		"Tasting": "mar.18",
		"Host": "mj",
		"MJ": "18,0",
		"HS": "16,5",
		"BAL": "",
		"LPW": "16,5",
		"NIB": "16,0",
		"JR": "17,0",
		"Score": "16,80"
	},
	{
		"Wine": "Antinori Tignanello",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "March. Antinori",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "659",
		"Tasting": "mar.18",
		"Host": "mj",
		"MJ": "17,0",
		"HS": "16,5",
		"BAL": "",
		"LPW": "16,0",
		"NIB": "16,0",
		"JR": "17,0",
		"Score": "16,50"
	},
	{
		"Wine": "Pecchenino San Luigi Dogliani",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Pecchenino",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "152,9",
		"Tasting": "sep.17",
		"Host": "mj",
		"MJ": "16,0",
		"HS": "16,5",
		"BAL": "16,6",
		"LPW": "",
		"NIB": "",
		"JR": "16,6",
		"Score": "16,43"
	},
	{
		"Wine": "Ch. Musar",
		"Type": "Rodvin",
		"Year": "2009",
		"Producer": "Gaston Hochar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "320",
		"Tasting": "apr.18",
		"Host": "mj",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "",
		"LPW": "",
		"NIB": "17,0",
		"JR": "16,5",
		"Score": "16,38"
	},
	{
		"Wine": "Ch. Musar",
		"Type": "Rodvin",
		"Year": "2010",
		"Producer": "Gaston Hochar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "350",
		"Tasting": "apr.18",
		"Host": "mj",
		"MJ": "15,0",
		"HS": "16,5",
		"BAL": "",
		"LPW": "",
		"NIB": "16,5",
		"JR": "16,0",
		"Score": "16,00"
	},
	{
		"Wine": "Ch. Sociando-Mallet",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Sociando Mallet",
		"Area": "Bourdeax",
		"Country": "Frankrike",
		"Price": "380,8",
		"Tasting": "mar.18",
		"Host": "mj",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "",
		"LPW": "14,0",
		"NIB": "16,0",
		"JR": "15,0",
		"Score": "15,20"
	},
	{
		"Wine": "Riecine La Gioia",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Riecine S.S.",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "540,6",
		"Tasting": "mar.18",
		"Host": "mj",
		"MJ": "15,0",
		"HS": "16,0",
		"BAL": "",
		"LPW": "14,4",
		"NIB": "15,0",
		"JR": "15,5",
		"Score": "15,18"
	},
	{
		"Wine": "Felisia Berardenga",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Fatt. di Felsina",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "164,9",
		"Tasting": "sep.17",
		"Host": "mj",
		"MJ": "15,5",
		"HS": "15,0",
		"BAL": "15,0",
		"LPW": "",
		"NIB": "",
		"JR": "15,0",
		"Score": "15,13"
	},
	{
		"Wine": "Ch. Musar Ana",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Gaston Hochar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "250",
		"Tasting": "apr.18",
		"Host": "mj",
		"MJ": "",
		"HS": "14,5",
		"BAL": "",
		"LPW": "",
		"NIB": "15,5",
		"JR": "14,5",
		"Score": "14,83"
	},
	{
		"Wine": "Villa Antinori",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "March. Antinori",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "185",
		"Tasting": "mar.18",
		"Host": "mj",
		"MJ": "12,5",
		"HS": "14,5",
		"BAL": "",
		"LPW": "14,5",
		"NIB": "14,0",
		"JR": "14,0",
		"Score": "13,90"
	},
	{
		"Wine": "Suertes del Marques",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Bod.Suertes del Marqu√©s-Soagra",
		"Area": "Tenerife",
		"Country": "Spania",
		"Price": "229,9",
		"Tasting": "sep.17",
		"Host": "mj",
		"MJ": "14,0",
		"HS": "13,5",
		"BAL": "14,0",
		"LPW": "",
		"NIB": "",
		"JR": "14,0",
		"Score": "13,88"
	},
	{
		"Wine": "Lenoble Chouilly Blanc de Bhes Grand Cry 2008",
		"Type": "Champagne",
		"Year": "2008",
		"Producer": "A.R. Lenoble",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "699,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "16,0",
		"HS": "17,0",
		"BAL": "",
		"LPW": "17,5",
		"NIB": "15,5",
		"JR": "17,5",
		"Score": "16,70"
	},
	{
		"Wine": "Ulysse Collin Les Pierri√®res Blanch De Blancs Extra Brut",
		"Type": "Champagne",
		"Year": "2016",
		"Producer": "Ulysse Collin",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "699,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "17,5",
		"BAL": "",
		"LPW": "17",
		"NIB": "15,5",
		"JR": "17,0",
		"Score": "16,50"
	},
	{
		"Wine": "Pouillon Les Blanchiens But Nature 2010",
		"Type": "Champagne",
		"Year": "2010",
		"Producer": "Roger Pouillon",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "544,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "16,0",
		"HS": "17,0",
		"BAL": "",
		"LPW": "16,5",
		"NIB": "15,5",
		"JR": "16,5",
		"Score": "16,30"
	},
	{
		"Wine": "Voulette & Sorbee Blanc d`Argile Extra Brut",
		"Type": "Champagne",
		"Year": "2017",
		"Producer": "Dom. Voulette et Sorb√®e",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "639,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "",
		"LPW": "16,5",
		"NIB": "15,0",
		"JR": "16,5",
		"Score": "16,00"
	},
	{
		"Wine": "Cline Sonoma Coast Pinot Noir",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Cline",
		"Area": "California",
		"Country": "USA",
		"Price": "179,9",
		"Tasting": "Oct. 17",
		"Host": "lpw",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "16,0",
		"LPW": "15,5",
		"NIB": "16,0",
		"JR": "16,0",
		"Score": "15,58"
	},
	{
		"Wine": "Ponnelle Mercurey",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Pierre Ponnelle",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "209,9",
		"Tasting": "Oct. 17",
		"Host": "lpw",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "14,5",
		"LPW": "16,0",
		"NIB": "14,0",
		"JR": "15,5",
		"Score": "15,00"
	},
	{
		"Wine": "Francis Ford Coppola Diamond Collection Chardonnay",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Francis Ford Coppola Winery",
		"Area": "California",
		"Country": "USA",
		"Price": "226,5",
		"Tasting": "Oct. 17",
		"Host": "lpw",
		"MJ": "14,0",
		"HS": "14,5",
		"BAL": "15,5",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "15,0",
		"Score": "15,00"
	},
	{
		"Wine": "Claude Cazales Blanch de Blances Grand Cry Cuve√®",
		"Type": "Champagne",
		"Year": "2017",
		"Producer": "Claude Casales",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "342,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "15,0",
		"HS": "14,5",
		"BAL": "",
		"LPW": "15",
		"NIB": "14,5",
		"JR": "15,0",
		"Score": "14,80"
	},
	{
		"Wine": "Fourny Vertus Blanc de Blancs Brut Nature",
		"Type": "Champagne",
		"Year": "2017",
		"Producer": "Vve Fourny",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "334,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "14,5",
		"HS": "15,0",
		"BAL": "",
		"LPW": "14,5",
		"NIB": "14,0",
		"JR": "15,0",
		"Score": "14,60"
	},
	{
		"Wine": "Dom. De Mouscaillo Cremant de Limoux",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Dom. De Mouscaillo",
		"Area": "Langedoc",
		"Country": "Frankrike",
		"Price": "214",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "15,0",
		"HS": "14,5",
		"BAL": "",
		"LPW": "13,5",
		"NIB": "14,0",
		"JR": "14,5",
		"Score": "14,30"
	},
	{
		"Wine": "Deux Roches Plants du Carre M√¢con",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Collowray & Terrier",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "169,9",
		"Tasting": "Oct. 17",
		"Host": "lpw",
		"MJ": "13,5",
		"HS": "14,0",
		"BAL": "15,5",
		"LPW": "14,0",
		"NIB": "15,0",
		"JR": "13,5",
		"Score": "14,25"
	},
	{
		"Wine": "Wongraven Champagne Brut",
		"Type": "Champagne",
		"Year": "2014",
		"Producer": "Wongraven Wines",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "339,9",
		"Tasting": "jun.18",
		"Host": "lpw",
		"MJ": "13,5",
		"HS": "13,5",
		"BAL": "",
		"LPW": "12",
		"NIB": "12,0",
		"JR": "14,0",
		"Score": "13,00"
	},
	{
		"Wine": "Rolet Arbois",
		"Type": "Hvitvin",
		"Year": "2004",
		"Producer": "Rolet Pere et Fils",
		"Area": "Jura",
		"Country": "Frankrike",
		"Price": "N/A",
		"Tasting": "aug.18",
		"Host": "jrl",
		"MJ": "N/A",
		"HS": "N/A",
		"BAL": "N/A",
		"LPW": "N/A",
		"NIB": "N/A",
		"JR": "N/A",
		"Score": "N/A"
	},
	{
		"Wine": "Mormoreto Castello di Nipozzano",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Frescobaldi",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "649",
		"Tasting": "jan.18",
		"Host": "jrl",
		"MJ": "17,0",
		"HS": "17,0",
		"BAL": "17,5",
		"LPW": "17",
		"NIB": "16,5",
		"JR": "17,5",
		"Score": "17,08"
	},
	{
		"Wine": "Brizio Brunello di Montalcino 2012",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "Podere Brizio",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "429",
		"Tasting": "jan.18",
		"Host": "jrl",
		"MJ": "16,5",
		"HS": "17,0",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "17,0",
		"JR": "17,0",
		"Score": "16,75"
	},
	{
		"Wine": "F√®lsina Fontalloro",
		"Type": "Rodvin",
		"Year": "2011",
		"Producer": "F√®lsina",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "420",
		"Tasting": "jan.18",
		"Host": "jrl",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "17,5",
		"LPW": "16",
		"NIB": "17,0",
		"JR": "16,0",
		"Score": "16,42"
	},
	{
		"Wine": "Tissot La Mailloche",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Andr√© et Mireille Tissot",
		"Area": "Jura",
		"Country": "Frankrike",
		"Price": "419,19",
		"Tasting": "aug.18",
		"Host": "jrl",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "16",
		"LPW": "16,5",
		"NIB": "16,0",
		"JR": "17,0",
		"Score": "16,25"
	},
	{
		"Wine": "Dom. du P√©lican Arbois",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Dom. du P√©lican",
		"Area": "Jura",
		"Country": "Frankrike",
		"Price": "399,9",
		"Tasting": "aug.18",
		"Host": "jrl",
		"MJ": "15,5",
		"HS": "16,0",
		"BAL": "17",
		"LPW": "16,5",
		"NIB": "15,5",
		"JR": "16,0",
		"Score": "16,08"
	},
	{
		"Wine": "Tyler Santa Barbara County",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Tyler Winery",
		"Area": "California",
		"Country": "USA",
		"Price": "250",
		"Tasting": "aug.18",
		"Host": "jrl",
		"MJ": "15,0",
		"HS": "14,5",
		"BAL": "15,5",
		"LPW": "15",
		"NIB": "13,0",
		"JR": "15,0",
		"Score": "14,67"
	},
	{
		"Wine": "Rolet C√¥tes du Jura La dent de Charnet",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Dom. Rolet et Flls",
		"Area": "Jura",
		"Country": "Frankrike",
		"Price": "219",
		"Tasting": "aug.18",
		"Host": "jrl",
		"MJ": "14,0",
		"HS": "15,0",
		"BAL": "15",
		"LPW": "15",
		"NIB": "14,0",
		"JR": "14,5",
		"Score": "14,58"
	},
	{
		"Wine": "Ch. de Puligny-Montrachet Bourgogne Clos du Chateau",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Ch. de Puligny-Montrachet",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "359,9",
		"Tasting": "aug.18",
		"Host": "jrl",
		"MJ": "15,0",
		"HS": "14,0",
		"BAL": "14,5",
		"LPW": "14",
		"NIB": "14,5",
		"JR": "14,0",
		"Score": "14,33"
	},
	{
		"Wine": "F√®lsina Chianti Classico",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "F√®lsina",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "170",
		"Tasting": "jan.18",
		"Host": "jrl",
		"MJ": "14,5",
		"HS": "14,5",
		"BAL": "15",
		"LPW": "14",
		"NIB": "13,5",
		"JR": "14,5",
		"Score": "14,33"
	},
	{
		"Wine": "Le Boncie",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Giovanna Morganti",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "259",
		"Tasting": "jan.18",
		"Host": "jrl",
		"MJ": "14,5",
		"HS": "14,0",
		"BAL": "15,5",
		"LPW": "13",
		"NIB": "14,0",
		"JR": "14,5",
		"Score": "14,25"
	},
	{
		"Wine": "Costadoro Lo Puro",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Soc. Agr. Costadoro",
		"Area": "Marche",
		"Country": "Italia",
		"Price": "129",
		"Tasting": "jan.18",
		"Host": "jrl",
		"MJ": "13,5",
		"HS": "13,5",
		"BAL": "14",
		"LPW": "13",
		"NIB": "15,0",
		"JR": "14,5",
		"Score": "13,92"
	},
	{
		"Wine": "Charles Heidseck Blanc du Mill√©naires",
		"Type": "Champagne",
		"Year": "1995",
		"Producer": "Charles Heidseck",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "1050",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "18,5",
		"HS": "19,5",
		"BAL": "19,0",
		"LPW": "19,5",
		"NIB": "18,5",
		"JR": "19,0",
		"Score": "19,00"
	},
	{
		"Wine": "Dom Perignon",
		"Type": "Champagne",
		"Year": "1995",
		"Producer": "Moet et Chandon",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "830",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "18,0",
		"HS": "19,0",
		"BAL": "19,0",
		"LPW": "19,5",
		"NIB": "18,0",
		"JR": "19,0",
		"Score": "18,75"
	},
	{
		"Wine": "Blanc de Blanc Brut (Chetillons)",
		"Type": "Champagne",
		"Year": "1996",
		"Producer": "Pierre Peters",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "350",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "17,5",
		"HS": "18,0",
		"BAL": "18,5",
		"LPW": "17,5",
		"NIB": "17,0",
		"JR": "17,5",
		"Score": "17,67"
	},
	{
		"Wine": "Henriot Millisieme Brut",
		"Type": "Champagne",
		"Year": "1996",
		"Producer": "Henriot",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "550",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "18,0",
		"HS": "18,0",
		"BAL": "17,5",
		"LPW": "17",
		"NIB": "17,5",
		"JR": "17,0",
		"Score": "17,50"
	},
	{
		"Wine": "Clos-Vougeot Vieilles Vignes Sui Generis",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Dominique Laurent",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "995",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "16,0",
		"HS": "17,5",
		"BAL": "17,0",
		"LPW": "17,0",
		"NIB": "17,0",
		"JR": "18,0",
		"Score": "17,08"
	},
	{
		"Wine": "Bucaco Tinto",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Palace Hotel",
		"Area": "Beiras",
		"Country": "Portugal",
		"Price": "450",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "16,5",
		"HS": "16,0",
		"BAL": "16,5",
		"LPW": "17,0",
		"NIB": "16,5",
		"JR": "17,0",
		"Score": "16,58"
	},
	{
		"Wine": "Zeltinger Zonnenuhr Auslese *** T√∏rr",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Molitor",
		"Area": "Mosel",
		"Country": "Tyskland",
		"Price": "630",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "15,0",
		"HS": "17,5",
		"BAL": "17,5",
		"LPW": "17,0",
		"NIB": "15,5",
		"JR": "16,5",
		"Score": "16,50"
	},
	{
		"Wine": "Barolo Vigna Rionda",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Roagna",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "400",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "16,5",
		"HS": "17,0",
		"BAL": "16,5",
		"LPW": "15,0",
		"NIB": "16,5",
		"JR": "17,0",
		"Score": "16,42"
	},
	{
		"Wine": "Trimbach Riesling Cuvee Frederic Emilie",
		"Type": "Hvitvin",
		"Year": "2008",
		"Producer": "F.E. Trimbach",
		"Area": "Alsace",
		"Country": "Frankrike",
		"Price": "459",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "16,5",
		"HS": "17,5",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "16,5",
		"Score": "16,33"
	},
	{
		"Wine": "Lanson Gold Label Brut",
		"Type": "Champagne",
		"Year": "2002",
		"Producer": "Lanson",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "455",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "17,0",
		"LPW": "16,5",
		"NIB": "16,0",
		"JR": "16,5",
		"Score": "16,33"
	},
	{
		"Wine": "Clos Cazals",
		"Type": "Champagne",
		"Year": "2002",
		"Producer": "Clos Cazals",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "754",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "17,5",
		"BAL": "17,0",
		"LPW": "16",
		"NIB": "16,0",
		"JR": "15,5",
		"Score": "16,25"
	},
	{
		"Wine": "Millisieme Grand Cru",
		"Type": "Champagne",
		"Year": "1996",
		"Producer": "Pierre Peters",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "300",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "17,5",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "16",
		"NIB": "16,0",
		"JR": "16,5",
		"Score": "16,17"
	},
	{
		"Wine": "Zeltinger Zonnenuhr Auslese *** T√∏rr",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Molitor",
		"Area": "Mosel",
		"Country": "Tyskland",
		"Price": "660",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "16,0",
		"HS": "17,0",
		"BAL": "17",
		"LPW": "16,5",
		"NIB": "15,5",
		"JR": "15,0",
		"Score": "16,17"
	},
	{
		"Wine": "Ch Cantemerle",
		"Type": " Bordeaux",
		"Year": "R",
		"Producer": "2004",
		"Area": "Cantermerle",
		"Country": "Bourdeax",
		"Price": "Frankrike",
		"Tasting": "560",
		"Host": "nov.18",
		"MJ": "hs",
		"HS": "15,0",
		"BAL": "16,5",
		"LPW": "16,0",
		"NIB": "16,0",
		"JR": "16,0",
		"Score": "17,0"
	},
	{
		"Wine": "Barbaresco Vanotu",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Pelissero",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "450",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "15,0",
		"HS": "16,0",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "17,5",
		"Score": "16,00"
	},
	{
		"Wine": "La Chapelle du Clos",
		"Type": "Champagne",
		"Year": "NV",
		"Producer": "Clos Cazals",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "535",
		"Tasting": "jun.17",
		"Host": "hs",
		"MJ": "14,5",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "16,5",
		"JR": "14,5",
		"Score": "15,75"
	},
	{
		"Wine": "Zeltinger Zonnenuhr Auslese ** T√∏rr",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "Molitor",
		"Area": "Mosel",
		"Country": "Tyskland",
		"Price": "364",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "16,0",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "15,0",
		"JR": "15,5",
		"Score": "15,67"
	},
	{
		"Wine": "Taurasi Riserva Vigna Cinque Querce",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Molettieri",
		"Area": "Taurasi",
		"Country": "Italia",
		"Price": "375",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "16,0",
		"LPW": "15,5",
		"NIB": "15,0",
		"JR": "15,0",
		"Score": "15,42"
	},
	{
		"Wine": "Zeltinger Zonnenuhr Sp√§tlese T√∏rr",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Molitor",
		"Area": "Mosel",
		"Country": "Tyskland",
		"Price": "225",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "15",
		"HS": "16,0",
		"BAL": "16",
		"LPW": "15,0",
		"NIB": "14,5",
		"JR": "14,5",
		"Score": "15,17"
	},
	{
		"Wine": "Brunello di Montalcino",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Casanova di Neri",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "380",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "13,5",
		"HS": "15,5",
		"BAL": "15,0",
		"LPW": "15,0",
		"NIB": "15,0",
		"JR": "16,5",
		"Score": "15,08"
	},
	{
		"Wine": "Zind-Humbrecht Riesling Brand Grand Cru",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Zind-Humbrecht",
		"Area": "Alsace",
		"Country": "Frankrike",
		"Price": "300",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "15,0",
		"HS": "16,0",
		"BAL": "16",
		"LPW": "14,5",
		"NIB": "14,0",
		"JR": "14,0",
		"Score": "14,92"
	},
	{
		"Wine": "Trimbach Geisberg Grand Cru Riesling",
		"Type": "Hvitvin",
		"Year": "2011",
		"Producer": "F.E. Trimbach",
		"Area": "Alsace",
		"Country": "Frankrike",
		"Price": "499",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "16,0",
		"BAL": "14,5",
		"LPW": "14,0",
		"NIB": "15,0",
		"JR": "14,5",
		"Score": "14,92"
	},
	{
		"Wine": "Rioja Gran Reserva",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Gregorio Mart√≠nez",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "250",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "15,0",
		"HS": "14,5",
		"BAL": "14,5",
		"LPW": "15,0",
		"NIB": "15,0",
		"JR": "15,0",
		"Score": "14,83"
	},
	{
		"Wine": "Le Sid Cahors 2004",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Cosse Maisonneuve",
		"Area": "Cahore",
		"Country": "Frankrike",
		"Price": "215",
		"Tasting": "nov.18",
		"Host": "hs",
		"MJ": "14,0",
		"HS": "15,0",
		"BAL": "15,0",
		"LPW": "15,0",
		"NIB": "14,5",
		"JR": "14,5",
		"Score": "14,67"
	},
	{
		"Wine": "Trimbach Selection Vielles Vignes",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "F.E. Trimbach",
		"Area": "Alsace",
		"Country": "Frankrike",
		"Price": "299",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "14,5",
		"NIB": "14,0",
		"JR": "13,0",
		"Score": "14,50"
	},
	{
		"Wine": "Trimbach Riesling",
		"Type": "Hvitvin",
		"Year": "2016",
		"Producer": "F.E. Trimbach",
		"Area": "Alsace",
		"Country": "Frankrike",
		"Price": "180",
		"Tasting": "jun.18",
		"Host": "hs",
		"MJ": "14,0",
		"HS": "15,0",
		"BAL": "14,5",
		"LPW": "14,0",
		"NIB": "13,0",
		"JR": "14,0",
		"Score": "14,08"
	},
	{
		"Wine": "Leroux Gevrey Chambertin Vieilles Vignes",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Benjamin Leroux",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "476",
		"Tasting": "Oct. 18",
		"Host": "bal",
		"MJ": "17,5",
		"HS": "17,5",
		"BAL": "17,5",
		"LPW": "17,5",
		"NIB": "17,0",
		"JR": "17,5",
		"Score": "17,42"
	},
	{
		"Wine": "Joseph Phelps Freestone Pinot Noir",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Joseph Phelps Vineyards",
		"Area": "California",
		"Country": "USA",
		"Price": "400",
		"Tasting": "Oct. 18",
		"Host": "bal",
		"MJ": "16,0",
		"HS": "17,0",
		"BAL": "17,0",
		"LPW": "17,0",
		"NIB": "17,0",
		"JR": "17,0",
		"Score": "16,83"
	},
	{
		"Wine": "Mahana Gravity Pinot Noir",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Concealed Wines AS",
		"Area": "Nelson",
		"Country": "New Zealand",
		"Price": "245",
		"Tasting": "aug.17",
		"Host": "bal",
		"MJ": "16,5",
		"HS": "17,0",
		"BAL": "16,5",
		"LPW": "16,6",
		"NIB": "15,5",
		"JR": "16,5",
		"Score": "16,43"
	},
	{
		"Wine": "Babcock Santa Barbara Pinot Noir",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Babcock Vineyards",
		"Area": "California",
		"Country": "USA",
		"Price": "180",
		"Tasting": "aug.17",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "16,0",
		"LPW": "16,5",
		"NIB": "15,0",
		"JR": "16,0",
		"Score": "15,75"
	},
	{
		"Wine": "Moestue Volnay",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Jean-Yves Devevey",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "453",
		"Tasting": "Oct. 18",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "15,0",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "15,0",
		"Score": "15,50"
	},
	{
		"Wine": "Chevrot Maranges Sur le Ch√™ne",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Dom. Chevrot",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "320",
		"Tasting": "Oct. 18",
		"Host": "bal",
		"MJ": "15,0",
		"HS": "15,5",
		"BAL": "16,0",
		"LPW": "15,5",
		"NIB": "15,0",
		"JR": "15,5",
		"Score": "15,42"
	},
	{
		"Wine": "Roche De Bellene Bourgogne Pinot Noir Vieilles Vignes",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Maison Roche de Bellene",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "190",
		"Tasting": "aug.17",
		"Host": "bal",
		"MJ": "15,0",
		"HS": "15,0",
		"BAL": "16,0",
		"LPW": "15,0",
		"NIB": "14,5",
		"JR": "15,0",
		"Score": "15,08"
	},
	{
		"Wine": "Cline Sonoma Coast Pinot Noir",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Cline",
		"Area": "California",
		"Country": "USA",
		"Price": "179,9",
		"Tasting": "aug.17",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "14,5",
		"BAL": "",
		"LPW": "14,5",
		"NIB": "14",
		"JR": "15,0",
		"Score": "14,70"
	},
	{
		"Wine": "Patrice Rion Bourgogne Rouge",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Dom. Patrice Rion",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "245",
		"Tasting": "aug.17",
		"Host": "bal",
		"MJ": "13,0",
		"HS": "13,5",
		"BAL": "16,5",
		"LPW": "16,0",
		"NIB": "14,0",
		"JR": "15,0",
		"Score": "14,67"
	},
	{
		"Wine": "Juillot Mercurey Clos Tonnerre",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Domaine Michel Juillot",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "300",
		"Tasting": "Oct. 18",
		"Host": "bal",
		"MJ": "14,0",
		"HS": "14,0",
		"BAL": "14,5",
		"LPW": "14,5",
		"NIB": "13,5",
		"JR": "14,5",
		"Score": "14,17"
	},
	{
		"Wine": "Louis Chenu Savigny Vieilles Vignes",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Louis Chenu P√®re et Filles",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "340",
		"Tasting": "Oct. 18",
		"Host": "bal",
		"MJ": "13,0",
		"HS": "14,0",
		"BAL": "14,0",
		"LPW": "13,5",
		"NIB": "14,5",
		"JR": "14,0",
		"Score": "13,83"
	},
	{
		"Wine": "Matua Hawke's Bay Syrah",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Matua Wines",
		"Area": "Hawke's Bay",
		"Country": "New Zealand",
		"Price": "144,9",
		"Tasting": "aug.17",
		"Host": "bal",
		"MJ": "13,5",
		"HS": "14,5",
		"BAL": "13,0",
		"LPW": "14,0",
		"NIB": "8,5",
		"JR": "14,5",
		"Score": "13,00"
	},
	{
		"Wine": "Dom. des Tourelles 2014",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Dom. des Tourelles",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "179,9",
		"Tasting": "jan.19",
		"Host": "mj",
		"MJ": "14,0",
		"HS": "13,5",
		"BAL": "14,5",
		"LPW": "13,5",
		"NIB": "14,5",
		"JR": "14,5",
		"Score": "14,08"
	},
	{
		"Wine": "Chateau Dudon",
		"Type": "Rodvin",
		"Year": "2009",
		"Producer": "Ch. Dudon",
		"Area": "Bourdeaux",
		"Country": "Frankrike",
		"Price": "152",
		"Tasting": "jan.19",
		"Host": "mj",
		"MJ": "14,5",
		"HS": "14,0",
		"BAL": "14,0",
		"LPW": "14,5",
		"NIB": "14,0",
		"JR": "14,5",
		"Score": "14,25"
	},
	{
		"Wine": "Ch. Kefraya Les Bret√®ches",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Ch. Kefraya",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "150",
		"Tasting": "jan.19",
		"Host": "mj",
		"MJ": "15,0",
		"HS": "15,0",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "15,0",
		"JR": "15,5",
		"Score": "15,42"
	},
	{
		"Wine": "Dom. des Tourelles Cinsault Vieilles Vignes",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Dom. des Tourelles",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "269,9",
		"Tasting": "jan.19",
		"Host": "mj",
		"MJ": "13,5",
		"HS": "13,5",
		"BAL": "14,5",
		"LPW": "15,5",
		"NIB": "13,5",
		"JR": "14,5",
		"Score": "14,17"
	},
	{
		"Wine": "Ch. Ksara",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Ch. Ksara",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "275",
		"Tasting": "jan.19",
		"Host": "mj",
		"MJ": "15,5",
		"HS": "16,0",
		"BAL": "16,5",
		"LPW": "16,0",
		"NIB": "15,5",
		"JR": "16,0",
		"Score": "15,92"
	},
	{
		"Wine": "Dom. des Tourelles Marquis des Beys",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Dom. des Tourelles",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "324,9",
		"Tasting": "jan.19",
		"Host": "mj",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "16,5",
		"LPW": "15,0",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,25"
	},
	{
		"Wine": "Ch Musar",
		"Type": "Rodvin",
		"Year": "2011",
		"Producer": "Ch Musar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "375",
		"Tasting": "aug.19",
		"Host": "hs",
		"MJ": "",
		"HS": "15,5",
		"BAL": "15,0",
		"LPW": "16,0",
		"NIB": "15,0",
		"JR": "15,5",
		"Score": "15,40"
	},
	{
		"Wine": "Barbaresco",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Paroccho de Neive",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "375",
		"Tasting": "aug.19",
		"Host": "hs",
		"MJ": "",
		"HS": "16,0",
		"BAL": "15,0",
		"LPW": "16,5",
		"NIB": "14,0",
		"JR": "17,0",
		"Score": "15,70"
	},
	{
		"Wine": "Ch Cantemerle",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Cantemerle",
		"Area": "Bourdeax",
		"Country": "Frankrike",
		"Price": "540",
		"Tasting": "aug.19",
		"Host": "hs",
		"MJ": "",
		"HS": "16,5",
		"BAL": "16,0",
		"LPW": "17,0",
		"NIB": "14,0",
		"JR": "14,0",
		"Score": "15,50"
	},
	{
		"Wine": "Beaunes 1.cru",
		"Type": " Clos de Ursules",
		"Year": "R",
		"Producer": "2016",
		"Area": "Louis Jadot",
		"Country": "Bourdeax",
		"Price": "Frankrike",
		"Tasting": "750",
		"Host": "aug.19",
		"MJ": "hs",
		"HS": "",
		"BAL": "16,5",
		"LPW": "14,0",
		"NIB": "16,0",
		"JR": "15,0",
		"Score": "13,5"
	},
	{
		"Wine": "Ch Cantemerle",
		"Type": "Rodvin",
		"Year": "2004",
		"Producer": "Cantemerle",
		"Area": "Bourdeax",
		"Country": "Frankrike",
		"Price": "560",
		"Tasting": "aug.19",
		"Host": "hs",
		"MJ": "",
		"HS": "16,0",
		"BAL": "17,5",
		"LPW": "17,0",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,70"
	},
	{
		"Wine": "Ch Musar",
		"Type": "Rodvin",
		"Year": "2003",
		"Producer": "Ch Musar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "440",
		"Tasting": "aug.19",
		"Host": "hs",
		"MJ": "",
		"HS": "17,0",
		"BAL": "18,0",
		"LPW": "17,5",
		"NIB": "17,0",
		"JR": "18,5",
		"Score": "17,60"
	},
	{
		"Wine": "Beaunes 1.cru",
		"Type": " Chouacheux",
		"Year": "R",
		"Producer": "2002",
		"Area": "Louis Jadot",
		"Country": "Bourdeax",
		"Price": "Frankrike",
		"Tasting": "390",
		"Host": "aug.19",
		"MJ": "hs",
		"HS": "",
		"BAL": "17,5",
		"LPW": "17,0",
		"NIB": "18,0",
		"JR": "15,0",
		"Score": "17,5"
	},
	{
		"Wine": "Harbard Crozes-Hermitage",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "",
		"Area": "",
		"Country": "Frankrike",
		"Price": "244,9",
		"Tasting": "sep.19",
		"Host": "lpw",
		"MJ": "",
		"HS": "14,5",
		"BAL": "15",
		"LPW": "12",
		"NIB": "",
		"JR": "15",
		"Score": "14,13"
	},
	{
		"Wine": "Colombier Crozes-Hermitage",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "",
		"Area": "",
		"Country": "Frankrike",
		"Price": "234,9",
		"Tasting": "sep.19",
		"Host": "lpw",
		"MJ": "",
		"HS": "15,5",
		"BAL": "16",
		"LPW": "15",
		"NIB": "",
		"JR": "15,5",
		"Score": "15,50"
	},
	{
		"Wine": "Graillot Crozes-Hermitage",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "",
		"Area": "",
		"Country": "Frankrike",
		"Price": "303",
		"Tasting": "sep.19",
		"Host": "lpw",
		"MJ": "",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "16",
		"NIB": "",
		"JR": "16",
		"Score": "16,13"
	},
	{
		"Wine": "Dom. Coursodon Silic",
		"Type": " ST Joseph",
		"Year": "R",
		"Producer": "2016",
		"Area": "",
		"Country": "",
		"Price": "Frankrike",
		"Tasting": "300",
		"Host": "sep.19",
		"MJ": "",
		"HS": "",
		"BAL": "15,5",
		"LPW": "16",
		"NIB": "15,5",
		"JR": "0",
		"Score": "16"
	},
	{
		"Wine": "Cap Nord",
		"Type": " Combier Crozes-Hermitage",
		"Year": "R",
		"Producer": "2016",
		"Area": "",
		"Country": "",
		"Price": "Frankrike",
		"Tasting": "337,5",
		"Host": "sep.19",
		"MJ": "",
		"HS": "",
		"BAL": "16",
		"LPW": "17,5",
		"NIB": "17",
		"JR": "0",
		"Score": "16"
	},
	{
		"Wine": "Dom. Du Colombier",
		"Type": " Hermitage",
		"Year": "R",
		"Producer": "2015",
		"Area": "",
		"Country": "",
		"Price": "Frankrike",
		"Tasting": "599,9",
		"Host": "sep.19",
		"MJ": "",
		"HS": "",
		"BAL": "17",
		"LPW": "17",
		"NIB": "17,5",
		"JR": "0",
		"Score": "17"
	},
	{
		"Wine": "Gatinara",
		"Type": " travaglini",
		"Year": "R",
		"Producer": "2015",
		"Area": "Giancarlo Travaglini",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "239,9",
		"Host": "okt.19",
		"MJ": "nib",
		"HS": "14,5",
		"BAL": "15",
		"LPW": "15",
		"NIB": "12",
		"JR": "15",
		"Score": "15"
	},
	{
		"Wine": "Dehesa la Granja",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Bod. Alejandro Fernandez",
		"Area": "Castilla y Le√≥n",
		"Country": "Spania",
		"Price": "159",
		"Tasting": "okt.19",
		"Host": "nib",
		"MJ": "14,5",
		"HS": "14,5",
		"BAL": "14,5",
		"LPW": "12,5",
		"NIB": "14,5",
		"JR": "14,5",
		"Score": "14,17"
	},
	{
		"Wine": "Barolo",
		"Type": " bon Padre",
		"Year": " Viberti",
		"Producer": "R",
		"Area": "2015",
		"Country": "Viberti Giovanni",
		"Price": "Piemonte",
		"Tasting": "Italia",
		"Host": "329",
		"MJ": "okt.19",
		"HS": "nib",
		"BAL": "15",
		"LPW": "14,5",
		"NIB": "15,5",
		"JR": "14",
		"Score": "15,5"
	},
	{
		"Wine": "Barolo",
		"Type": " reserva bussia Fenocchio",
		"Year": "R",
		"Producer": "2012",
		"Area": "Fenocchio",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "309,9",
		"Host": "okt.19",
		"MJ": "nib",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,5"
	},
	{
		"Wine": "Gattinara",
		"Type": "R",
		"Year": " conterno",
		"Producer": "R",
		"Area": "2015",
		"Country": "Luigi Nervi",
		"Price": "Piemonte",
		"Tasting": "Italia",
		"Host": "379,9",
		"MJ": "okt.19",
		"HS": "nib",
		"BAL": "17",
		"LPW": "17,5",
		"NIB": "17",
		"JR": "17",
		"Score": "16,5"
	},
	{
		"Wine": "Gattinara",
		"Type": "R",
		"Year": " Nervi",
		"Producer": " Conterno",
		"Area": "R",
		"Country": "2014",
		"Price": "Luigi Nervi",
		"Tasting": "Piemonte",
		"Host": "Italia",
		"MJ": "949,9",
		"HS": "okt.19",
		"BAL": "nib",
		"LPW": "17",
		"NIB": "16",
		"JR": "16",
		"Score": "15,5"
	},
	{
		"Wine": "Vina Tondina Reserva",
		"Type": "Rodvin",
		"Year": "2006",
		"Producer": "Lopez de Heredia",
		"Area": "Rioja",
		"Country": "Spania",
		"Price": "329,90",
		"Tasting": "okt.19",
		"Host": "bal",
		"MJ": "13,5",
		"HS": "14",
		"BAL": "15",
		"LPW": "14",
		"NIB": "14",
		"JR": "0",
		"Score": "14,10"
	},
	{
		"Wine": "Finca Valpiedra Reserva",
		"Type": "Rodvin",
		"Year": "2001",
		"Producer": "Finca Valpiedra",
		"Area": "Rioja",
		"Country": "Spania",
		"Price": "397,20",
		"Tasting": "okt.19",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "16",
		"JR": "0",
		"Score": "16,00"
	},
	{
		"Wine": "Ch. Soudars",
		"Type": "Rodvin",
		"Year": "2005",
		"Producer": "Ch. Soudars",
		"Area": "Bordeax",
		"Country": "Frankrike",
		"Price": "300,00",
		"Tasting": "okt.19",
		"Host": "bal",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "16,5",
		"NIB": "16,5",
		"JR": "0",
		"Score": "16,60"
	},
	{
		"Wine": "Ch. Bel-Air Lagrave",
		"Type": "Rodvin",
		"Year": "1985",
		"Producer": "Ch. Ble-Air Lagrave",
		"Area": "Bordeax",
		"Country": "Frankrike",
		"Price": "399,90",
		"Tasting": "okt.19",
		"Host": "bal",
		"MJ": "16",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "16",
		"NIB": "16",
		"JR": "0",
		"Score": "16,10"
	},
	{
		"Wine": "Fontarollo",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Felsina",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "429,90",
		"Tasting": "okt.19",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "16",
		"BAL": "17",
		"LPW": "16",
		"NIB": "17",
		"JR": "0",
		"Score": "16,30"
	},
	{
		"Wine": "Radici Taurasi Riserva",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "Mastroberadino",
		"Area": "Campania",
		"Country": "Italia",
		"Price": "459,90",
		"Tasting": "okt.19",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "17",
		"BAL": "17,5",
		"LPW": "17",
		"NIB": "17,5",
		"JR": "0",
		"Score": "16,90"
	},
	{
		"Wine": "Scarpa Barbera d'Asti I Bricchi",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Scarpa",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "289,9",
		"Tasting": "jan.20",
		"Host": "jrl",
		"MJ": "14",
		"HS": "15",
		"BAL": "14,5",
		"LPW": "",
		"NIB": "",
		"JR": "15",
		"Score": "14,63"
	},
	{
		"Wine": "Scarpa Barbaresco Tettineive",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Scarpa",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "578",
		"Tasting": "jan.20",
		"Host": "jrl",
		"MJ": "15",
		"HS": "16",
		"BAL": "15,5",
		"LPW": "",
		"NIB": "",
		"JR": "16,5",
		"Score": "15,75"
	},
	{
		"Wine": "Scarpa Barbera d'Asti La Bogliona",
		"Type": "Rodvin",
		"Year": "2011",
		"Producer": "Scarpa",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "459,9",
		"Tasting": "jan.20",
		"Host": "jrl",
		"MJ": "15",
		"HS": "16,5",
		"BAL": "16,5",
		"LPW": "",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,13"
	},
	{
		"Wine": "Prodotori del Barbaresco",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Prodotori",
		"Area": "Piemionte",
		"Country": "Italia",
		"Price": "349,9",
		"Tasting": "jan.20",
		"Host": "jrl",
		"MJ": "16",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,50"
	},
	{
		"Wine": "Scarpa Barbera d'Asti Bogliona",
		"Type": "Rodvin",
		"Year": "2008",
		"Producer": "Scarpa",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "396",
		"Tasting": "jan.20",
		"Host": "jrl",
		"MJ": "16,5",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,38"
	},
	{
		"Wine": "Barolo Bussia Reserva",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Fenocchio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "320",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "13,5",
		"HS": "16,0",
		"BAL": "15,5",
		"LPW": "15,5",
		"NIB": "14,5",
		"JR": "15,0",
		"Score": "15,00"
	},
	{
		"Wine": "Barbaresco Reserva Paje",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Produttori",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "310",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "16,0",
		"LPW": "14,5",
		"NIB": "14,5",
		"JR": "15,0",
		"Score": "15,17"
	},
	{
		"Wine": "Barbaresco Reserva Paje",
		"Type": "Rodvin",
		"Year": "2007",
		"Producer": "Produttori",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "300",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "15,0",
		"HS": "16,5",
		"BAL": "17,0",
		"LPW": "16,0",
		"NIB": "16,0",
		"JR": "15,5",
		"Score": "16,00"
	},
	{
		"Wine": "Barolo Bussia Reserva",
		"Type": "Rodvin",
		"Year": "2007",
		"Producer": "Fenocchio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "300",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "16,0",
		"LPW": "16,5",
		"NIB": "15,5",
		"JR": "16,0",
		"Score": "16,00"
	},
	{
		"Wine": "Barbaresco Reserva Ovello",
		"Type": "Rodvin",
		"Year": "2001",
		"Producer": "Produttori",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "280",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "17,0",
		"HS": "17,0",
		"BAL": "16,5",
		"LPW": "16,0",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,58"
	},
	{
		"Wine": "Barolo Bussia Reserva",
		"Type": "Rodvin",
		"Year": "2001",
		"Producer": "Fenocchio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "280",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "17,0",
		"HS": "17,0",
		"BAL": "17,5",
		"LPW": "16,5",
		"NIB": "17,0",
		"JR": "17,0",
		"Score": "17,00"
	},
	{
		"Wine": "Barolo Bussia Reserva",
		"Type": "Rodvin",
		"Year": "1996",
		"Producer": "Fenocchio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "250",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "17,0",
		"HS": "17,5",
		"BAL": "17,5",
		"LPW": "17,5",
		"NIB": "17,0",
		"JR": "17,5",
		"Score": "17,33"
	},
	{
		"Wine": "Barbaresco Reserva Asili",
		"Type": "Rodvin",
		"Year": "1996",
		"Producer": "Produttori",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "240",
		"Tasting": "feb.20",
		"Host": "hs",
		"MJ": "17,0",
		"HS": "18,0",
		"BAL": "17,0",
		"LPW": "18,0",
		"NIB": "17,0",
		"JR": "18,0",
		"Score": "17,50"
	},
	{
		"Wine": "Georg Breuer Sp√§tburgunder Rouge",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Georg Breuer",
		"Area": "Rheingau",
		"Country": "Tyskland",
		"Price": "243,9",
		"Tasting": "mai.20",
		"Host": "lpw",
		"MJ": "14",
		"HS": "15",
		"BAL": "",
		"LPW": "15",
		"NIB": "",
		"JR": "15,5",
		"Score": "14,88"
	},
	{
		"Wine": "K√ºnstler Hocheim Stein Pinot Noir Grosses Gew√§chs",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Gunter K√ºnstler",
		"Area": "Rheingau",
		"Country": "Tyskland",
		"Price": "350",
		"Tasting": "mai.20",
		"Host": "lpw",
		"MJ": "16",
		"HS": "16",
		"BAL": "",
		"LPW": "15,5",
		"NIB": "",
		"JR": "16",
		"Score": "15,88"
	},
	{
		"Wine": "Weing Th√∂rle H√∂lle Sp√§tburgunder",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Winzerhof Th√∂rle",
		"Area": "",
		"Country": "Tyskland",
		"Price": "399",
		"Tasting": "mai.20",
		"Host": "lpw",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "",
		"LPW": "17",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,63"
	},
	{
		"Wine": "Walldorf Sp√§tburgunder Saulheim",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Weingut Walldorf Paffenhof",
		"Area": "Rheinhessen",
		"Country": "Tyskland",
		"Price": "395",
		"Tasting": "mai.20",
		"Host": "lpw",
		"MJ": "16",
		"HS": "16,5",
		"BAL": "",
		"LPW": "16,5",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,38"
	},
	{
		"Wine": "Dr.Wehrheim Kastanienbush K√∂ppel Sp√§tburgunder Trocken GG",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Winzerhof Th√∂rle",
		"Area": "Pfalz",
		"Country": "Tyskland",
		"Price": "409,9",
		"Tasting": "mai.20",
		"Host": "lpw",
		"MJ": "17",
		"HS": "17",
		"BAL": "",
		"LPW": "17",
		"NIB": "",
		"JR": "17",
		"Score": "17,00"
	},
	{
		"Wine": "Kloster Eberbach Assmannsh√§user Crescentia H√∂llenberg Sp√§tburgunder",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Kloster Eberbach",
		"Area": "Rheingau",
		"Country": "Tyskland",
		"Price": "299,9",
		"Tasting": "mai.20",
		"Host": "lpw",
		"MJ": "16",
		"HS": "16,5",
		"BAL": "",
		"LPW": "17",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,50"
	},
	{
		"Wine": "Pieper heidiesec Rare",
		"Type": "Champagne",
		"Year": "",
		"Producer": "Piper-Heidsieck",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "1399,9",
		"Tasting": "jun.20",
		"Host": "nib",
		"MJ": "15",
		"HS": "16",
		"BAL": "15,5",
		"LPW": "16",
		"NIB": "16",
		"JR": "16",
		"Score": "15,75"
	},
	{
		"Wine": "A.D.Coutelas Grand",
		"Type": "Champagne",
		"Year": "",
		"Producer": "A.D. Coutelas",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "589",
		"Tasting": "jun.20",
		"Host": "nib",
		"MJ": "15",
		"HS": "14,5",
		"BAL": "15,5",
		"LPW": "14,5",
		"NIB": "15,5",
		"JR": "15,5",
		"Score": "15,08"
	},
	{
		"Wine": "J.Telmont Herita",
		"Type": "Champagne",
		"Year": "",
		"Producer": "J. de Telmont",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "1111",
		"Tasting": "jun.20",
		"Host": "nib",
		"MJ": "15",
		"HS": "16",
		"BAL": "16",
		"LPW": "15",
		"NIB": "17",
		"JR": "15",
		"Score": "15,67"
	},
	{
		"Wine": "Beurton-Vincent Res√©",
		"Type": "Champagne",
		"Year": "",
		"Producer": "Champagne Beurton-Vincent",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "297",
		"Tasting": "jun.20",
		"Host": "nib",
		"MJ": "15,5",
		"HS": "17",
		"BAL": "17",
		"LPW": "16,5",
		"NIB": "16",
		"JR": "16,5",
		"Score": "16,42"
	},
	{
		"Wine": "Gusborne brut",
		"Type": "Champagne",
		"Year": "2014",
		"Producer": "Gusbourne Estate",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "399,9",
		"Tasting": "jun.20",
		"Host": "nib",
		"MJ": "17,5",
		"HS": "17,5",
		"BAL": "18",
		"LPW": "17,5",
		"NIB": "17,5",
		"JR": "17,5",
		"Score": "17,58"
	},
	{
		"Wine": "Hur√© Fr√®res 4 Elements Chardonnay",
		"Type": "Champagne",
		"Year": "",
		"Producer": "Hur√® Fr√®res",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "719,9",
		"Tasting": "jun.20",
		"Host": "nib",
		"MJ": "18",
		"HS": "16",
		"BAL": "NA",
		"LPW": "15,5",
		"NIB": "17,5",
		"JR": "17",
		"Score": "16,80"
	},
	{
		"Wine": "Nervi Rosato 2019",
		"Type": "RO",
		"Year": "2019",
		"Producer": "Az. Vit. Nervi s.r.l.",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "199,9",
		"Tasting": "aug.20",
		"Host": "MJ",
		"MJ": "14",
		"HS": "14",
		"BAL": "",
		"LPW": "14",
		"NIB": "13",
		"JR": "14",
		"Score": "13,80"
	},
	{
		"Wine": "Wongraven Senza Compromesso",
		"Type": "RO",
		"Year": "2018",
		"Producer": "Wongraven Wines",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "189,9",
		"Tasting": "aug.20",
		"Host": "MJ",
		"MJ": "12",
		"HS": "12,5",
		"BAL": "",
		"LPW": "10,5",
		"NIB": "10",
		"JR": "12",
		"Score": "11,40"
	},
	{
		"Wine": "Henri Bourgeois Sancerre Les Baronnes",
		"Type": "RO",
		"Year": "2019",
		"Producer": "Henri Bourgeois",
		"Area": "Loire",
		"Country": "Frankrike",
		"Price": "209,9",
		"Tasting": "aug.20",
		"Host": "MJ",
		"MJ": "15",
		"HS": "14",
		"BAL": "",
		"LPW": "14,5",
		"NIB": "14",
		"JR": "14,5",
		"Score": "14,40"
	},
	{
		"Wine": "Whispering Angel Cotes de Provence",
		"Type": "RO",
		"Year": "2019",
		"Producer": "d'Esclans - Sacha Lichine",
		"Area": "Provence",
		"Country": "Frankrike",
		"Price": "259,9",
		"Tasting": "aug.20",
		"Host": "MJ",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "",
		"LPW": "16",
		"NIB": "14,5",
		"JR": "15,5",
		"Score": "15,40"
	},
	{
		"Wine": "Vacheron Le Ros√© XVII",
		"Type": "RO",
		"Year": "2019",
		"Producer": "Dom. Vacheron",
		"Area": "√òvrige",
		"Country": "Frankrike",
		"Price": "",
		"Tasting": "aug.20",
		"Host": "MJ",
		"MJ": "15",
		"HS": "15",
		"BAL": "",
		"LPW": "15,5",
		"NIB": "15",
		"JR": "15,5",
		"Score": "15,20"
	},
	{
		"Wine": "Winiveria Saperavi",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Winiveria",
		"Area": "√òvrige",
		"Country": "Moldova",
		"Price": "210",
		"Tasting": "Oct. 21",
		"Host": "jrl",
		"MJ": "14",
		"HS": "14,5",
		"BAL": "15,5",
		"LPW": "14,5",
		"NIB": "15",
		"JR": "15,5",
		"Score": "14,83"
	},
	{
		"Wine": "La Spinetta Ca' di Pian Barbera d'Asti Superiore",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Az. Agr. La Spinetta",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "299",
		"Tasting": "Oct. 21",
		"Host": "jrl",
		"MJ": "14,5",
		"HS": "15",
		"BAL": "15",
		"LPW": "15",
		"NIB": "15,5",
		"JR": "15",
		"Score": "15,00"
	},
	{
		"Wine": "La Spinetta Barbaresco Bordini 2018",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Az. Agr. La Spinetta",
		"Area": "Piemonta",
		"Country": "Italia",
		"Price": "499",
		"Tasting": "Oct. 21",
		"Host": "jrl",
		"MJ": "15,5",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "16",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,17"
	},
	{
		"Wine": "Ethno Saperavi",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Ethno, Wine Art",
		"Area": "√òvierige",
		"Country": "Moldova",
		"Price": "280",
		"Tasting": "Oct. 21",
		"Host": "jrl",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "15",
		"LPW": "14,5",
		"NIB": "15",
		"JR": "16",
		"Score": "15,08"
	},
	{
		"Wine": "La Spinetta Barolo Garretti",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Az. Agr. La Spinetta",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "570",
		"Tasting": "Oct. 21",
		"Host": "jrl",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "16,5",
		"LPW": "15",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,25"
	},
	{
		"Wine": "Gurashvili's Kindzmarauli",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Gura",
		"Area": "√òvrige",
		"Country": "Moldova",
		"Price": "265",
		"Tasting": "Oct. 21",
		"Host": "jrl",
		"MJ": "14,5",
		"HS": "16",
		"BAL": "15",
		"LPW": "14,5",
		"NIB": "15",
		"JR": "15,5",
		"Score": "15,08"
	},
	{
		"Wine": "Haddow Dineen Private Universe Pinot Noir",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Haddow + Dineen Wine",
		"Area": "Tasmania",
		"Country": "Australia",
		"Price": "415",
		"Tasting": "Sep, 21",
		"Host": "bal",
		"MJ": "14",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "16",
		"NIB": "15,5",
		"JR": "0",
		"Score": "15,30"
	},
	{
		"Wine": "Schlumberger-Bemhart Wingerte Pinot Noir",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Privat-Weingut Schlumberger-Bernhart",
		"Area": "Baden",
		"Country": "Tyskland",
		"Price": "429",
		"Tasting": "Sep, 21",
		"Host": "bal",
		"MJ": "15",
		"HS": "15",
		"BAL": "14,5",
		"LPW": "14,5",
		"NIB": "14,5",
		"JR": "0",
		"Score": "14,70"
	},
	{
		"Wine": "Scherrer Russian River Valley Pinot Noir",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Scherrer winery",
		"Area": "California",
		"Country": "USA",
		"Price": "499",
		"Tasting": "Sep, 21",
		"Host": "bal",
		"MJ": "15",
		"HS": "16,5",
		"BAL": "16",
		"LPW": "16",
		"NIB": "16",
		"JR": "0",
		"Score": "15,90"
	},
	{
		"Wine": "Fa iveley Gevrey-Chambertin Vieilles Vignes",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Dom. Faiveley",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "445",
		"Tasting": "Sep, 21",
		"Host": "bal",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "16",
		"NIB": "16,5",
		"JR": "0",
		"Score": "16,50"
	},
	{
		"Wine": "Hirsch San Andreas Fault Pinot Noir",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Hirsch Vineyards",
		"Area": "California",
		"Country": "USA",
		"Price": "619",
		"Tasting": "Sep, 21",
		"Host": "bal",
		"MJ": "15,5",
		"HS": "16",
		"BAL": "17,5",
		"LPW": "17,5",
		"NIB": "17",
		"JR": "0",
		"Score": "16,70"
	},
	{
		"Wine": "Patrice Rion Chambolle-Musigny Vieilles Vignes",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Rion, Domaine Mich√®le et Patrice",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "680",
		"Tasting": "Sep, 21",
		"Host": "bal",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "17",
		"NIB": "17",
		"JR": "0",
		"Score": "16,80"
	},
	{
		"Wine": "Vi√∫va Gomes Colares",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "Adega Viuva Gomes",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "349,9",
		"Tasting": "Sep, 21",
		"Host": "lpw",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "15",
		"LPW": "15",
		"NIB": "14",
		"JR": "14,5",
		"Score": "14,75"
	},
	{
		"Wine": "Colares Chitas",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "A. Bernardino Paulo da Silva",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "481,2",
		"Tasting": "jun.21",
		"Host": "lpw",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "15",
		"LPW": "15,5",
		"NIB": "14",
		"JR": "14,5",
		"Score": "14,83"
	},
	{
		"Wine": "Colares Chitas",
		"Type": "Rodvin",
		"Year": "2001",
		"Producer": "A. Bernardino Paulo da Silva",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "461,5",
		"Tasting": "jun.21",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "15",
		"BAL": "15",
		"LPW": "16",
		"NIB": "14,5",
		"JR": "15,5",
		"Score": "15,25"
	},
	{
		"Wine": "Vi√∫va Gomes Colares",
		"Type": "Rodvin",
		"Year": "1969",
		"Producer": "Adega Viuva Gomes",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "899,9",
		"Tasting": "jun.21",
		"Host": "lpw",
		"MJ": "17",
		"HS": "17",
		"BAL": "17,5",
		"LPW": "17",
		"NIB": "17,5",
		"JR": "18",
		"Score": "17,33"
	},
	{
		"Wine": "Vi√∫va Gomes Colares",
		"Type": "Rodvin",
		"Year": "1967",
		"Producer": "Adega Viuva Gomes",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "1000",
		"Tasting": "jun.21",
		"Host": "lpw",
		"MJ": "17",
		"HS": "17,5",
		"BAL": "18",
		"LPW": "18",
		"NIB": "18",
		"JR": "18,5",
		"Score": "17,83"
	},
	{
		"Wine": "Vi√∫va Gomes Colares",
		"Type": "Rodvin",
		"Year": "1965",
		"Producer": "Adega Viuva Gomes",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "1200",
		"Tasting": "jun.21",
		"Host": "lpw",
		"MJ": "17,5",
		"HS": "18",
		"BAL": "18,5",
		"LPW": "18",
		"NIB": "18,5",
		"JR": "18",
		"Score": "18,08"
	},
	{
		"Wine": "Vi√∫va Gomes Colares",
		"Type": "Rodvin",
		"Year": "1934",
		"Producer": "Adega Viuva Gomes",
		"Area": "Colares",
		"Country": "Portugal",
		"Price": "1684,3",
		"Tasting": "jun.21",
		"Host": "lpw",
		"MJ": "18",
		"HS": "18",
		"BAL": "18",
		"LPW": "18",
		"NIB": "18",
		"JR": "18,5",
		"Score": "18,08"
	},
	{
		"Wine": "Musar Jeune",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Ch Musar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "229,9",
		"Tasting": "jan.22",
		"Host": "mj",
		"MJ": "13",
		"HS": "15,5",
		"BAL": "",
		"LPW": "",
		"NIB": "13",
		"JR": "15",
		"Score": "14,13"
	},
	{
		"Wine": "Fenocchio Barolo Bussia Sottana Riserva",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Fenocchio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "345,9",
		"Tasting": "jan.22",
		"Host": "mj",
		"MJ": "16",
		"HS": "16,5",
		"BAL": "",
		"LPW": "",
		"NIB": "16",
		"JR": "16,5",
		"Score": "16,25"
	},
	{
		"Wine": "Ch Musar",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Ch Musar",
		"Area": "Bekaa Valley",
		"Country": "Libanon",
		"Price": "449,9",
		"Tasting": "jan.22",
		"Host": "mj",
		"MJ": "15",
		"HS": "15,5",
		"BAL": "",
		"LPW": "",
		"NIB": "15",
		"JR": "15",
		"Score": "15,13"
	},
	{
		"Wine": "Piemonte Barbera - kartong",
		"Type": "Rodvin",
		"Year": "2021",
		"Producer": "N/A",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "450",
		"Tasting": "jan.22",
		"Host": "mj",
		"MJ": "14",
		"HS": "13,5",
		"BAL": "",
		"LPW": "",
		"NIB": "14",
		"JR": "13",
		"Score": "13,63"
	},
	{
		"Wine": "Vi√±a Cubillo Crianza",
		"Type": "Rodvin",
		"Year": "2013",
		"Producer": "Lopez de Heredia",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "260",
		"Tasting": "apr.22",
		"Host": "jrl",
		"MJ": "14,5",
		"HS": "14,5",
		"BAL": "15",
		"LPW": "14",
		"NIB": "14,5",
		"JR": "15,5",
		"Score": "14,67"
	},
	{
		"Wine": "CVNE Imperial Reserva",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "CVNE",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "339",
		"Tasting": "apr.22",
		"Host": "jrl",
		"MJ": "15,5",
		"HS": "16",
		"BAL": "15,5",
		"LPW": "15,5",
		"NIB": "14",
		"JR": "16",
		"Score": "15,42"
	},
	{
		"Wine": "Ch. Bel-Air Lagrave",
		"Type": "Rodvin",
		"Year": "1995",
		"Producer": "Ch. Bel Air Lagrave",
		"Area": "Bordeaux",
		"Country": "Frankrike",
		"Price": "400",
		"Tasting": "apr.22",
		"Host": "jrl",
		"MJ": "17,5",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "17",
		"NIB": "16",
		"JR": "17",
		"Score": "16,83"
	},
	{
		"Wine": "Vi√±a Tondonia Reserva",
		"Type": "Rodvin",
		"Year": "2009",
		"Producer": "Lopez de Heredia",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "379",
		"Tasting": "apr.22",
		"Host": "jrl",
		"MJ": "18",
		"HS": "18,5",
		"BAL": "18",
		"LPW": "17,5",
		"NIB": "17,5",
		"JR": "17,5",
		"Score": "17,83"
	},
	{
		"Wine": "Lopez de Heredia Vi√±a Bosconia",
		"Type": "Rodvin",
		"Year": "2010",
		"Producer": "Lopez de Heredia",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "369",
		"Tasting": "apr.22",
		"Host": "jrl",
		"MJ": "17,5",
		"HS": "17,5",
		"BAL": "18",
		"LPW": "18",
		"NIB": "18",
		"JR": "18",
		"Score": "17,83"
	},
	{
		"Wine": "Vi√±a Tondonia G.Reserva",
		"Type": "Rodvin",
		"Year": "1978",
		"Producer": "Lopez de Heredia",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "255",
		"Tasting": "apr.22",
		"Host": "jrl",
		"MJ": "18,5",
		"HS": "18,5",
		"BAL": "18,5",
		"LPW": "18,5",
		"NIB": "18",
		"JR": "18,5",
		"Score": "18,42"
	},
	{
		"Wine": "Vin 1",
		"Type": "Rodvin",
		"Year": "N/A",
		"Producer": "N/A",
		"Area": "N/A",
		"Country": "Sør Afrika",
		"Price": "N/A",
		"Tasting": "mar.22",
		"Host": "nib",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "15,5",
		"NIB": "15,5",
		"JR": "15,5",
		"Score": "15,33"
	},
	{
		"Wine": "Vin 2",
		"Type": "Rodvin",
		"Year": "N/A",
		"Producer": "N/A",
		"Area": "N/A",
		"Country": "Sør Afrika",
		"Price": "N/A",
		"Tasting": "mar.22",
		"Host": "nib",
		"MJ": "15,5",
		"HS": "15",
		"BAL": "15",
		"LPW": "15",
		"NIB": "15,5",
		"JR": "15,5",
		"Score": "15,25"
	},
	{
		"Wine": "Vin 3",
		"Type": "Rodvin",
		"Year": "N/A",
		"Producer": "N/A",
		"Area": "N/A",
		"Country": "Sør Afrika",
		"Price": "N/A",
		"Tasting": "mar.22",
		"Host": "nib",
		"MJ": "16",
		"HS": "15,5",
		"BAL": "16",
		"LPW": "15,5",
		"NIB": "15",
		"JR": "15",
		"Score": "15,50"
	},
	{
		"Wine": "Vin 4",
		"Type": "Rodvin",
		"Year": "N/A",
		"Producer": "N/A",
		"Area": "N/A",
		"Country": "Sør Afrika",
		"Price": "N/A",
		"Tasting": "mar.22",
		"Host": "nib",
		"MJ": "16,5",
		"HS": "17",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,58"
	},
	{
		"Wine": "Vin 5",
		"Type": "Rodvin",
		"Year": "N/A",
		"Producer": "N/A",
		"Area": "N/A",
		"Country": "Sør Afrika",
		"Price": "N/A",
		"Tasting": "mar.22",
		"Host": "nib",
		"MJ": "17",
		"HS": "17",
		"BAL": "17",
		"LPW": "17,5",
		"NIB": "17,5",
		"JR": "17,5",
		"Score": "17,25"
	},
	{
		"Wine": "Vin 6",
		"Type": "Rodvin",
		"Year": "N/A",
		"Producer": "N/A",
		"Area": "N/A",
		"Country": "Sør Afrika",
		"Price": "N/A",
		"Tasting": "mar.22",
		"Host": "nib",
		"MJ": "17,5",
		"HS": "18",
		"BAL": "17,5",
		"LPW": "18",
		"NIB": "18",
		"JR": "17",
		"Score": "17,67"
	},
	{
		"Wine": "Kuhn Sp√§tburgunder Tradition",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Philipp Kuhn",
		"Area": "Phalz",
		"Country": "Tyskland",
		"Price": "225",
		"Tasting": "oct.22",
		"Host": "mj",
		"MJ": "13",
		"HS": "14",
		"BAL": "",
		"LPW": "14",
		"NIB": "14",
		"JR": "13,5",
		"Score": "13,70"
	},
	{
		"Wine": "Brun Bourgogne Pinot Noir",
		"Type": "Rodvin",
		"Year": "2021",
		"Producer": "Jean-Paul Brun",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "299,9",
		"Tasting": "oct.22",
		"Host": "mj",
		"MJ": "14,5",
		"HS": "13,5",
		"BAL": "",
		"LPW": "12",
		"NIB": "13,5",
		"JR": "13,5",
		"Score": "13,40"
	},
	{
		"Wine": "Azul y Garanza Naturaleza Salvaje Clarete",
		"Type": "Rodvin",
		"Year": "2020",
		"Producer": "Azul y Garanza",
		"Area": "Navarra",
		"Country": "Spania",
		"Price": "269,9",
		"Tasting": "oct.22",
		"Host": "mj",
		"MJ": "15",
		"HS": "14,5",
		"BAL": "",
		"LPW": "14,5",
		"NIB": "15",
		"JR": "14,5",
		"Score": "14,70"
	},
	{
		"Wine": "Lejeune Month√©lie En Remagnien",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Dom. Lejeune",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "364",
		"Tasting": "oct.22",
		"Host": "mj",
		"MJ": "16",
		"HS": "15,5",
		"BAL": "",
		"LPW": "16",
		"NIB": "16",
		"JR": "15,5",
		"Score": "15,80"
	},
	{
		"Wine": "Sandhi Sta Rita Hills Pinot Noir",
		"Type": "Rodvin",
		"Year": "2020",
		"Producer": "Sandhi",
		"Area": "California",
		"Country": "USA",
		"Price": "",
		"Tasting": "oct.22",
		"Host": "mj",
		"MJ": "17",
		"HS": "15,5",
		"BAL": "",
		"LPW": "16,5",
		"NIB": "15,5",
		"JR": "16,5",
		"Score": "16,20"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2017",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "425",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "14,5",
		"BAL": "16",
		"LPW": "",
		"NIB": "16",
		"JR": "15,5",
		"Score": "16"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2016",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "425",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "15",
		"BAL": "17",
		"LPW": "",
		"NIB": "17",
		"JR": "15,5",
		"Score": "16"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2015",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "400",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "15,5",
		"BAL": "16,5",
		"LPW": "",
		"NIB": "16,5",
		"JR": "16",
		"Score": "16,5"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2014",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "355",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "15,5",
		"BAL": "16",
		"LPW": "",
		"NIB": "17",
		"JR": "17",
		"Score": "16,5"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2013",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "355",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "17",
		"BAL": "15,5",
		"LPW": "",
		"NIB": "17",
		"JR": "16,5",
		"Score": "16,5"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2011",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "340",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "17,5",
		"BAL": "16",
		"LPW": "",
		"NIB": "17",
		"JR": "16,5",
		"Score": "17"
	},
	{
		"Wine": "Barbaresco Reserva",
		"Type": " Ovello",
		"Year": "R",
		"Producer": "2001",
		"Area": "Produttori del Barbaresco",
		"Country": "Piemonte",
		"Price": "Italia",
		"Tasting": "250",
		"Host": "mai.22",
		"MJ": "hs",
		"HS": "17,5",
		"BAL": "18",
		"LPW": "",
		"NIB": "18",
		"JR": "17,5",
		"Score": "18"
	},
	{
		"Wine": "Villa Antinori",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "March. Antinori",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "205",
		"Tasting": "sep.22",
		"Host": "lpw",
		"MJ": "14",
		"HS": "15,5",
		"BAL": "16",
		"LPW": "15",
		"NIB": "15",
		"JR": "15,5",
		"Score": "15,17"
	},
	{
		"Wine": "Val delle Corti Chianti Classico Riserva",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Val delle Corti",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "456,4",
		"Tasting": "sep.22",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "16",
		"NIB": "15,5",
		"JR": "15",
		"Score": "15,50"
	},
	{
		"Wine": "Castello di Meleto Poggiarso Chianti Classico Gran Selezione",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Cast. de Meleto",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "449,9",
		"Tasting": "sep.22",
		"Host": "lpw",
		"MJ": "16",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "16,5",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,50"
	},
	{
		"Wine": "Rocca di Montegrossi San Marcellino Chianti Classico Gran Selezione",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Rocca di Montegrossi",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "456",
		"Tasting": "44805",
		"Host": "lpw",
		"MJ": "16,5",
		"HS": "16",
		"BAL": "17",
		"LPW": "17,5",
		"NIB": "16",
		"JR": "17",
		"Score": "16,67"
	},
	{
		"Wine": "Cast. di Ama Chianti Classico Gran Selezione San Lorenzo",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Cast. di Ama",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "485",
		"Tasting": "44805",
		"Host": "lpw",
		"MJ": "15",
		"HS": "16,5",
		"BAL": "16,5",
		"LPW": "17,5",
		"NIB": "16,5",
		"JR": "17,5",
		"Score": "16,58"
	},
	{
		"Wine": "Castell'in Villa Chianti Classico Riserva",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Castell'in Villa",
		"Area": "Toscana",
		"Country": "Italia",
		"Price": "599,9",
		"Tasting": "44805",
		"Host": "lpw",
		"MJ": "15",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "17,5",
		"NIB": "16",
		"JR": "17",
		"Score": "16,50"
	},
	{
		"Wine": "A.D. Coutelas Grand Millesime Brut",
		"Type": "Hvitvin",
		"Year": "2014",
		"Producer": "A.D. Coutelas",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "549",
		"Tasting": "44713",
		"Host": "bal",
		"MJ": "",
		"HS": "16",
		"BAL": "16",
		"LPW": "16",
		"NIB": "16",
		"JR": "16,5",
		"Score": "16,10"
	},
	{
		"Wine": "M. Vesselle Bouzy Grand Cru Extra Brut",
		"Type": "Hvitvin",
		"Year": "2008",
		"Producer": "M. Vesselle Bouzy Grand Cru Extra Brut",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "599",
		"Tasting": "44713",
		"Host": "bal",
		"MJ": "",
		"HS": "17,5",
		"BAL": "17",
		"LPW": "17",
		"NIB": "16,5",
		"JR": "17,5",
		"Score": "17,10"
	},
	{
		"Wine": "Mo√´t et Chandon Grand Vintage",
		"Type": "Hvitvin",
		"Year": "2013",
		"Producer": "Mo√´t & Chandon",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "599",
		"Tasting": "44713",
		"Host": "bal",
		"MJ": "",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "16",
		"NIB": "17",
		"JR": "17",
		"Score": "16,70"
	},
	{
		"Wine": "Joseph Perrier Champagne La C√¥te √† Bras",
		"Type": "Hvitvin",
		"Year": "N/A",
		"Producer": "Joseph Perrier",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "739",
		"Tasting": "44713",
		"Host": "bal",
		"MJ": "",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "16",
		"NIB": "17",
		"JR": "16,5",
		"Score": "16,60"
	},
	{
		"Wine": "Champagne Legras & Haas Les Sillons",
		"Type": "Hvitvin",
		"Year": "2015",
		"Producer": "Legras & Haas",
		"Area": "Champagne",
		"Country": "Frankrike",
		"Price": "748",
		"Tasting": "44713",
		"Host": "bal",
		"MJ": "",
		"HS": "18,5",
		"BAL": "18,5",
		"LPW": "18",
		"NIB": "18",
		"JR": "18",
		"Score": "18,20"
	},
	{
		"Wine": "Paul Launois Monochrome Champagne Blanc de Blancs",
		"Type": "Champagne",
		"Year": "2020",
		"Producer": "Scev Launois",
		"Area": "Champangne",
		"Country": "Frankrike",
		"Price": "549",
		"Tasting": "mar.23",
		"Host": "MJ",
		"MJ": "15",
		"HS": "16,5",
		"BAL": "15,5",
		"LPW": "",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,00"
	},
	{
		"Wine": "Gusbourne Blanc de Noirs",
		"Type": "Champagne",
		"Year": "2018",
		"Producer": "Gusbourne Estate",
		"Area": "Kent",
		"Country": "England",
		"Price": "599",
		"Tasting": "mar.23",
		"Host": "MJ",
		"MJ": "15",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,10"
	},
	{
		"Wine": "Bereche Cote Grand Cru",
		"Type": "Champagne",
		"Year": "2016",
		"Producer": "Bereche et Fils",
		"Area": "Champangne",
		"Country": "Frankrike",
		"Price": "813,3",
		"Tasting": "mar.23",
		"Host": "MJ",
		"MJ": "16",
		"HS": "17",
		"BAL": "17,5",
		"LPW": "",
		"NIB": "17",
		"JR": "17",
		"Score": "16,90"
	},
	{
		"Wine": "Pierre Paillard La Grande R√©colte Bouzy Grand Cru Extra Brut",
		"Type": "Champagne",
		"Year": "2012",
		"Producer": "Pierre Paillard",
		"Area": "Champangne",
		"Country": "Frankrike",
		"Price": "990",
		"Tasting": "mar.23",
		"Host": "MJ",
		"MJ": "17",
		"HS": "16,5",
		"BAL": "18",
		"LPW": "",
		"NIB": "18",
		"JR": "18",
		"Score": "17,50"
	},
	{
		"Wine": "Corbon √Ä Avize Grand Cru Mill√©sime 2009",
		"Type": "Champagne",
		"Year": "2009",
		"Producer": "Corbon",
		"Area": "Champangne",
		"Country": "Frankrike",
		"Price": "618",
		"Tasting": "mar.23",
		"Host": "MJ",
		"MJ": "18,5",
		"HS": "18",
		"BAL": "18",
		"LPW": "",
		"NIB": "18,5",
		"JR": "18,5",
		"Score": "18,30"
	},
	{
		"Wine": "Heimersheim Kapellenberg Sp√§tburgunder trocken",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Weinmanufaktur Dagernova",
		"Area": "Ahr",
		"Country": "Tyskland",
		"Price": "290",
		"Tasting": "jan.23",
		"Host": "JRL",
		"MJ": "14,5",
		"HS": "15,5",
		"BAL": "16",
		"LPW": "16,5",
		"NIB": "",
		"JR": "16",
		"Score": "15,70"
	},
	{
		"Wine": "K√ºnstler Hochheim Reichestal Pinot Noir Grosses Gew√§chs Trocken 2015",
		"Type": "Rodvin",
		"Year": "2015",
		"Producer": "Weing. K√ºnstler",
		"Area": "Reingau",
		"Country": "Tyskland",
		"Price": "499",
		"Tasting": "jan.23",
		"Host": "JRL",
		"MJ": "15,5",
		"HS": "14,5",
		"BAL": "15,5",
		"LPW": "15",
		"NIB": "",
		"JR": "15,5",
		"Score": "15,20"
	},
	{
		"Wine": "Rhys Alesia Anderson Valley Pinot Noir",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Hirsch Vineyards",
		"Area": "California",
		"Country": "USA",
		"Price": "499",
		"Tasting": "jan.23",
		"Host": "JRL",
		"MJ": "14,5",
		"HS": "15",
		"BAL": "14",
		"LPW": "13,5",
		"NIB": "",
		"JR": "15,5",
		"Score": "14,50"
	},
	{
		"Wine": "Salwey Eichberg Sp√§tburgunder GG",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Weing. Salwey",
		"Area": "Baden",
		"Country": "Tyskland",
		"Price": "599",
		"Tasting": "jan.23",
		"Host": "JRL",
		"MJ": "16,5",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "17",
		"NIB": "",
		"JR": "17",
		"Score": "16,80"
	},
	{
		"Wine": "Mark Haisma Pommard Premier Cru Clos des Arvelets",
		"Type": "Rodvin",
		"Year": "2014",
		"Producer": "Mark Haisma",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "710",
		"Tasting": "jan.23",
		"Host": "JRL",
		"MJ": "18",
		"HS": "17,5",
		"BAL": "17,5",
		"LPW": "17",
		"NIB": "",
		"JR": "17,5",
		"Score": "17,50"
	},
	{
		"Wine": "Roberto Voerzio Disanfrancesco Langhe Nebbiolo",
		"Type": "Rodvin",
		"Year": "2020",
		"Producer": "Az. Agr. Roberto Voerzio",
		"Area": "Lange",
		"Country": "Italia",
		"Price": "389,7",
		"Tasting": "44958",
		"Host": "lpw",
		"MJ": "14",
		"HS": "15,5",
		"BAL": "15,5",
		"LPW": "14,5",
		"NIB": "",
		"JR": "14",
		"Score": "14,70"
	},
	{
		"Wine": "Clendenen Bricco Buon Natale Nebbiolo",
		"Type": "Rodvin",
		"Year": "2017",
		"Producer": "Au Bon Climat Clenenden Family Vine",
		"Area": "California",
		"Country": "USA",
		"Price": "424,7",
		"Tasting": "44958",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "15",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "",
		"JR": "15,5",
		"Score": "15,60"
	},
	{
		"Wine": "Ronchi di Cialla Schioppettino",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "Ronchi di cialla",
		"Area": "Friuli-Venezia Giuli",
		"Country": "Italia",
		"Price": "399,9",
		"Tasting": "44958",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "16",
		"LPW": "16",
		"NIB": "",
		"JR": "15,5",
		"Score": "15,90"
	},
	{
		"Wine": "Sirch Schioppettino di Prepotto",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Sirch SARL",
		"Area": "Friuli-Venezia Giuli",
		"Country": "Italia",
		"Price": "253,7",
		"Tasting": "44958",
		"Host": "lpw",
		"MJ": "15",
		"HS": "15",
		"BAL": "15",
		"LPW": "15,5",
		"NIB": "",
		"JR": "16",
		"Score": "15,30"
	},
	{
		"Wine": "Ronco del Gnemiz Schiopettino",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Ronco del Gnemiz",
		"Area": "Friuli-Venezia Giuli",
		"Country": "Italia",
		"Price": "418,5",
		"Tasting": "44958",
		"Host": "lpw",
		"MJ": "15",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "16,5",
		"NIB": "",
		"JR": "16",
		"Score": "16,00"
	},
	{
		"Wine": "Ronchi di Cialla Schioppettino",
		"Type": "Rodvin",
		"Year": "2012",
		"Producer": "Ronchi di Cialla",
		"Area": "Friuli-Venezia Giuli",
		"Country": "Italia",
		"Price": "639",
		"Tasting": "44958",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "17",
		"BAL": "16",
		"LPW": "17",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,40"
	},
	{
		"Wine": "Premier Cru",
		"Type": " Brut Millisieme PN50/C50",
		"Year": "C",
		"Producer": "2015",
		"Area": "Roger Manceaux",
		"Country": "Chamagne",
		"Price": "Frankrike",
		"Tasting": "500",
		"Host": "jun.23",
		"MJ": "hs",
		"HS": "16,0",
		"BAL": "15,5",
		"LPW": "17,0",
		"NIB": "16,0",
		"JR": "15,5",
		"Score": "16,0"
	},
	{
		"Wine": "Les Sillons",
		"Type": " BdB",
		"Year": "C",
		"Producer": "2015",
		"Area": "Legras & Haas",
		"Country": "Chamagne",
		"Price": "Frankrike",
		"Tasting": "748",
		"Host": "jun.23",
		"MJ": "hs",
		"HS": "18,0",
		"BAL": "16,5",
		"LPW": "17,5",
		"NIB": "14,5",
		"JR": "15,5",
		"Score": "16,5"
	},
	{
		"Wine": "Premier Cru",
		"Type": " Brut Millisieme PN50/C50",
		"Year": "C",
		"Producer": "2012",
		"Area": "Roger Manceaux",
		"Country": "Chamagne",
		"Price": "Frankrike",
		"Tasting": "754",
		"Host": "jun.23",
		"MJ": "hs",
		"HS": "18,5",
		"BAL": "16,0",
		"LPW": "16,5",
		"NIB": "15,0",
		"JR": "16,0",
		"Score": "16,5"
	},
	{
		"Wine": "Brut Vintage PN60/40",
		"Type": "Champagne",
		"Year": "2008",
		"Producer": "Pol Roger",
		"Area": "Chamagne",
		"Country": "Frankrike",
		"Price": "400",
		"Tasting": "jun.23",
		"Host": "hs",
		"MJ": "18,0",
		"HS": "16,5",
		"BAL": "17,0",
		"LPW": "17,0",
		"NIB": "16,5",
		"JR": "16,5",
		"Score": "16,92"
	},
	{
		"Wine": "Fleur de Passion BdB",
		"Type": "Champagne",
		"Year": "2008",
		"Producer": "Diebolt-Vallois",
		"Area": "Chamagne",
		"Country": "Frankrike",
		"Price": "825",
		"Tasting": "jun.23",
		"Host": "hs",
		"MJ": "17,5",
		"HS": "17,5",
		"BAL": "17,5",
		"LPW": "17,0",
		"NIB": "16,5",
		"JR": "17,0",
		"Score": "17,17"
	},
	{
		"Wine": "Legras St.Vincent BdB",
		"Type": "Champagne",
		"Year": "2008",
		"Producer": "R&L Legras",
		"Area": "Chamagne",
		"Country": "Frankrike",
		"Price": "999",
		"Tasting": "jun.23",
		"Host": "hs",
		"MJ": "18,0",
		"HS": "18,5",
		"BAL": "17,5",
		"LPW": "16,5",
		"NIB": "16,5",
		"JR": "17,5",
		"Score": "17,42"
	},
	{
		"Wine": "Blanc du Mill√©naires",
		"Type": " BdB",
		"Year": "C",
		"Producer": "2004",
		"Area": "Charles Heidseck",
		"Country": "Chamagne",
		"Price": "Frankrike",
		"Tasting": "1450",
		"Host": "jun.23",
		"MJ": "hs",
		"HS": "16,0",
		"BAL": "18,5",
		"LPW": "19,0",
		"NIB": "17,5",
		"JR": "18,0",
		"Score": "18,5"
	},
	{
		"Wine": "Secr√©te Mill√©sime",
		"Type": " BdN (PN)",
		"Year": "C",
		"Producer": "1995",
		"Area": "Elodie D. Collection",
		"Country": "Chamagne",
		"Price": "Frankrike",
		"Tasting": "",
		"Host": "jun.23",
		"MJ": "hs",
		"HS": "",
		"BAL": "",
		"LPW": "",
		"NIB": "",
		"JR": "0",
		"Score": ""
	},
	{
		"Wine": "Blanc du Mill√©naires",
		"Type": " BdB",
		"Year": "C",
		"Producer": "1995",
		"Area": "Charles Heidseck",
		"Country": "Chamagne",
		"Price": "Frankrike",
		"Tasting": "1050",
		"Host": "jun.23",
		"MJ": "hs",
		"HS": "18,0",
		"BAL": "19,0",
		"LPW": "18,5",
		"NIB": "19,0",
		"JR": "18,0",
		"Score": "18,5"
	},
	{
		"Wine": "Vipava Lanthieri Pinot Noir",
		"Type": "Rodvin",
		"Year": "2020",
		"Producer": "Vipava",
		"Area": "",
		"Country": "Slovenia",
		"Price": "189,9",
		"Tasting": "aug.23",
		"Host": "lpw",
		"MJ": "14",
		"HS": "14,5",
		"BAL": "15",
		"LPW": "16",
		"NIB": "15",
		"JR": "0",
		"Score": "14,90"
	},
	{
		"Wine": "Marjan Sim?i? Opoka Cru Breg Pinot Noir",
		"Type": "Rodvin",
		"Year": "2018",
		"Producer": "Marjan Simcic",
		"Area": "",
		"Country": "Slovenia",
		"Price": "559,9",
		"Tasting": "aug.23",
		"Host": "lpw",
		"MJ": "15",
		"HS": "15",
		"BAL": "16,5",
		"LPW": "14",
		"NIB": "14",
		"JR": "0",
		"Score": "14,90"
	},
	{
		"Wine": "Burja Noir 2019",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Burja Estate",
		"Area": "",
		"Country": "Slovenia",
		"Price": "373,3",
		"Tasting": "aug.23",
		"Host": "lpw",
		"MJ": "15,5",
		"HS": "16,5",
		"BAL": "17",
		"LPW": "16",
		"NIB": "14,5",
		"JR": "0",
		"Score": "15,90"
	},
	{
		"Wine": "Marjan Sim?i? Cru Selection Pinot Noir",
		"Type": "Rodvin",
		"Year": "2020",
		"Producer": "Marjan Simcic",
		"Area": "",
		"Country": "Slovenia",
		"Price": "389,9",
		"Tasting": "aug.23",
		"Host": "lpw",
		"MJ": "16",
		"HS": "17",
		"BAL": "17,5",
		"LPW": "17,5",
		"NIB": "16",
		"JR": "0",
		"Score": "16,80"
	},
	{
		"Wine": "Pierre-Mayeul Givry",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Pierre-Mayeul",
		"Area": "Burgund",
		"Country": "Frankrike",
		"Price": "499,9",
		"Tasting": "aug.23",
		"Host": "lpw",
		"MJ": "17,5",
		"HS": "17,5",
		"BAL": "17",
		"LPW": "17,5",
		"NIB": "17",
		"JR": "0",
		"Score": "17,30"
	},
	{
		"Wine": "Veira Barbera",
		"Type": "Rodvin",
		"Year": "2022",
		"Producer": "G.D. Vajra",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "229,9",
		"Tasting": "sep.23",
		"Host": "mj",
		"MJ": "14",
		"HS": "15,5",
		"BAL": "15",
		"LPW": "",
		"NIB": "15",
		"JR": "14,5",
		"Score": "14,80"
	},
	{
		"Wine": "Borgogno Barbera",
		"Type": "Rodvin",
		"Year": "2022",
		"Producer": "Giacomo Borgogno & Figli",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "229,9",
		"Tasting": "sep.23",
		"Host": "mj",
		"MJ": "15",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "",
		"NIB": "14",
		"JR": "15,5",
		"Score": "15,40"
	},
	{
		"Wine": "Fausttino I",
		"Type": "Rodvin",
		"Year": "2011",
		"Producer": "Bod. Faustino",
		"Area": "Riocha",
		"Country": "Spania",
		"Price": "259,9",
		"Tasting": "sep.23",
		"Host": "mj",
		"MJ": "16",
		"HS": "16",
		"BAL": "15,5",
		"LPW": "",
		"NIB": "15",
		"JR": "16",
		"Score": "15,70"
	},
	{
		"Wine": "Fennochio Barolo Bussia",
		"Type": "Rodvin",
		"Year": "2016",
		"Producer": "Fenocchio",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "389,9",
		"Tasting": "sep.23",
		"Host": "mj",
		"MJ": "18",
		"HS": "18",
		"BAL": "18",
		"LPW": "",
		"NIB": "16,5",
		"JR": "18",
		"Score": "17,70"
	},
	{
		"Wine": "Prodotori Barbaresco",
		"Type": "Rodvin",
		"Year": "2019",
		"Producer": "Prod. del Barbaresco",
		"Area": "Piemonte",
		"Country": "Italia",
		"Price": "409,9",
		"Tasting": "sep.23",
		"Host": "mj",
		"MJ": "17",
		"HS": "17",
		"BAL": "17",
		"LPW": "",
		"NIB": "17",
		"JR": "16,5",
		"Score": "16,90"
	},
	{
		"Wine": "Balfour Leslies Reserve Brut",
		"Type": "Champagne",
		"Year": "",
		"Producer": "Balfour Winery",
		"Area": "Kent",
		"Country": "England",
		"Price": "397",
		"Tasting": "feb.24",
		"Host": "mj",
		"MJ": "13",
		"HS": "13,5",
		"BAL": "14",
		"LPW": "13,5",
		"NIB": "",
		"JR": "14",
		"Score": "13,60"
	},
	{
		"Wine": "Nyetimber Classic Cuvee",
		"Type": "Champagne",
		"Year": "",
		"Producer": "Nyetimber Limited",
		"Area": "",
		"Country": "England",
		"Price": "469,9",
		"Tasting": "feb.24",
		"Host": "mj",
		"MJ": "15",
		"HS": "15,5",
		"BAL": "16",
		"LPW": "15,5",
		"NIB": "",
		"JR": "15,5",
		"Score": "15,50"
	},
	{
		"Wine": "Raumland Blanc de Blancs Brut",
		"Type": "Champagne",
		"Year": "2018",
		"Producer": "Sekthaus Raumland",
		"Area": "Rhreinhessen",
		"Country": "Tyskland",
		"Price": "399,9",
		"Tasting": "feb.24",
		"Host": "mj",
		"MJ": "16",
		"HS": "16",
		"BAL": "16,5",
		"LPW": "15,5",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,10"
	},
	{
		"Wine": "Gusbourne Blanc de Blancs",
		"Type": "Champagne",
		"Year": "2018",
		"Producer": "Gusbourne Estate",
		"Area": "",
		"Country": "England",
		"Price": "499,9",
		"Tasting": "feb.24",
		"Host": "mj",
		"MJ": "17",
		"HS": "17",
		"BAL": "17",
		"LPW": "17",
		"NIB": "",
		"JR": "16,5",
		"Score": "16,90"
	},
	{
		"Wine": "Gusbourne Blanc de Noirs",
		"Type": "Champagne",
		"Year": "2018",
		"Producer": "Gusbourne Estate",
		"Area": "",
		"Country": "England",
		"Price": "639,5",
		"Tasting": "feb.24",
		"Host": "mj",
		"MJ": "17",
		"HS": "16,5",
		"BAL": "16,5",
		"LPW": "16",
		"NIB": "",
		"JR": "16",
		"Score": "16,40"
	}
]